### ISSUE TITLE
No error when using an unspecified function

### ISSUE THREAD

**Issue by chinedufn** [aputinski/butane#11]
Butane does not warn you when you attempt to use an undefined function. This seems error prone.
##### Current behavior

Input

``` yaml
.read: isWorker() # isWorker is not defined
```

Output

``` json
".read": "isWorker()"
```

Maybe throw an error here?

**Comment by aputinski** [comment]
@chinedufn Yeah, that seems like the right thing to do. I'll work on that today or tomorrow.

**Comment by chinedufn** [comment]
@aputinski sounds awesome! If you need a PR I'm fairly free so just ping

**Comment by aputinski** [comment]
@chinedufn If you have time to submit a PR that'd be great!

**Comment by chinedufn** [comment]
@aputinski on it :)
