### ISSUE TITLE
Add convertString function?

### ISSUE THREAD

**Issue by abeisgoat** [aputinski/butane#15]
It'd be great if we could have a convertString function that just takes a YAML string and returns the JSON string!

**Comment by aputinski** [comment]
@abeisgreat sure thing!

**Comment by aputinski** [comment]
@abeisgreat I just bumped to `3.0.0` and renamed `convert()` to `convertFile()`.

`convert()` now takes a YAML string and returns a JSON string

**Comment by abeisgoat** [comment]
Awesome, thanks bud! I was going to do it myself once I got a moment, but you beat me too it :)
