### ISSUE TITLE
Functions behave unusually with conditionals

### ISSUE THREAD

**Issue by abeisgoat** [aputinski/butane#16]
To me, it would seem that this...

```
.functions:
  isAuthed(): (auth !== null || auth.One)
  isOther(): (auth.Two || auth.Three) 
rules:
  .read: isAuthed() && isOther()'
```

... would evaluate to...

```
.read: "(auth !== null || auth.One) && (auth.Two || auth.Three)
```

... but it evaluates to...

```
.read: "auth !== null || auth.One && auth.Two || auth.Three"
```

... which has different results, however...

```
.read: (isAuthed()) && (isOther())
```

...does compile as expected. I think you could automatically wrap all function calls in parenthesis that way these logic issues are avoided. Thoughts?

**Comment by aputinski** [comment]
@abeisgreat if I compile (your example)

``` yaml
.functions:
  isAuthed(): auth !== null || auth.One
  isOther(): auth.Two || auth.Three
rules:
  .read: isAuthed() && isOther()
```

I get the following, which seems to be what you wanted?

``` json
{
  "rules": {
    ".read": "(auth !== null || auth.One) && (auth.Two || auth.Three)"
  }
}
```

**Comment by holgersindbaek** [comment]
I'm having the same issue... this:

```
.functions:
  isAuthed(): auth !== null
  isLoggedIn(): auth.uid !== null
  isUser(user): auth.uid === user
  isNewObject(): next.exists() && !prev.exists()
  isUpdateObject(): next.exists() && prev.exists()

rules:
  .read: true

  # USERS
  users:
    $user_id:
      .write: (isNewObject() && isAuthed()) || (isUpdateObject() && isUser($user_id))
```

Compiles to this:

```
{
  "rules": {
    ".read": true,
    "users": {
      "$user_id": {
        ".write": "newData.exists() && !data.exists() && auth !== null || newData.exists() && data.exists() && auth.uid === $user_id"
      }
    },
    "user_maps": {
      "facebook": {
        "$facebook_id": {
          ".read": "auth !== null",
          ".write": "newData.exists() && !data.exists() && auth !== null || newData.exists() && data.exists() && $facebook_id === root.child('users').child(data.val()).child('facebook_id').val()"
        }
      },
```

Any guess on what might be causing this?

**Comment by holgersindbaek** [comment]
@aputinski Would it work if I revert back to an older version? @abeisgreat What did you end up doing?

**Comment by holgersindbaek** [comment]
Just to be more clear. Here are my rules file:

https://gist.github.com/holgersindbaek/a2b62093f01ba4d710bd

And the compiled rules:

https://gist.github.com/holgersindbaek/f9f3b8697e0f02cfd6ab

And I'm on the newest version of Butane (3.0.0).

**Comment by aputinski** [comment]
@holgersindbaek I'll try to take a look this evening

**Comment by holgersindbaek** [comment]
Thanks... Looking forward to seeing what you come up with.

**Comment by abeisgoat** [comment]
Sorry about my delay in responding! @holgersindbaek I just ended up wrapping function calls in excessive parens and haven't dug into it since.

**Comment by holgersindbaek** [comment]
@aputinski Did you get to have a look at it?

**Comment by aputinski** [comment]
@holgersindbaek Sorry, things are a little crazy at work right now. Hopefully I can take a look this weekend. What version of node are you using?

**Comment by holgersindbaek** [comment]
v0.10.36

**Comment by aputinski** [comment]
@abeisgreat @holgersindbaek I've been doing some research:
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence
- http://stackoverflow.com/questions/11157814/which-logic-operator-takes-precedence

According to MDN, `Logical AND` has a precedence of **6** and `Logical OR` has a precedence of **5** (higher numbers having higher precedence). So, based on those rules, the following expressions are equal:

```
((newData.exists() && !data.exists()) && auth !== null) || ((newData.exists() && data.exists()) && auth.uid === $user_id)
```

```
newData.exists() && !data.exists() && auth !== null || newData.exists() && data.exists() && auth.uid === $user_id
```

Grouping operators have the highest priority (19), but escodegen is smart enough to rewrite the expression without the parenthesis. If you write an extremely complex expression where the parenthesis are needed, escodegen will preserve them.

@abeisgreat just to confirm, I think you may have pasted an incorrect example in the initial post:

If I compile:

``` yaml
.functions:
  isAuthed(): (auth !== null || auth.One)
  isOther(): (auth.Two || auth.Three) 
rules:
  .read: isAuthed() && isOther()
```

I get the rules that you had expected: 

``` json
{
  "rules": {
    ".read": "(auth !== null || auth.One) && (auth.Two || auth.Three)"
}
```

**Comment by holgersindbaek** [comment]
@aputinski Thanks a lot for the clarification. I would really like to keep the separators though. I find it very hard to read, if the separators are not there.

Is there any way I can keep the separators in there? Would it be hard to change the code, so I get to keep the separators in there?

**Comment by aputinski** [comment]
@holgersindbaek Unfortunately, no.

**Comment by holgersindbaek** [comment]
@aputinski And you're SURE that Firebase interprets operator precedence the same way?!

**Comment by aputinski** [comment]
@holgersindbaek I'm pretty sure, but I would reach out to the Firebase team for clarification.

/cc @gsoltis @davideast @mikelehen

**Comment by holgersindbaek** [comment]
@aputinski Just spoke with the Firebae people. This is what they have to say:

I'm fairly certain that operator precedence in the Firebase rules is the same as it is in regular JavaScript, so the parentheses are definitely important. It also just helps with code clarity to include them. So you should be explicit and wrap your example in parentheses. Otherwise, you will see unexpected results.

Seems like they are needed?! 

Really like Butane, but if it doesn't output correct rules, then it's a bit useless. 

—

**Comment by aputinski** [comment]
Just to clarify, butane is outputting the correct rules.

> I'm fairly certain that operator precedence in the Firebase rules is the same as it is in regular JavaScript, so the parentheses are definitely important.

I'm using two well supported libraries for parsing JavaScript expressions ([esprima](https://github.com/jquery/esprima)/[escodegen](https://github.com/estools/escodegen)). Escodegen will include parenthesis if they are needed. In the case of the example that you posted, the parenthesis only affect the readability, not the actual expression.

**Comment by holgersindbaek** [comment]
Hmm ok. Thanks a lot for clarifying.

-- 

All the best

Holger Sindbaek · UI/UX Designer & Web/iOS Programmer · HolgerSindbaek.com

**Comment by aputinski** [comment]
If I parse the following rules:

``` yaml
.functions:
  isAuthed(): auth !== null
  isUser(user): auth.uid === user
  isNewObject(): next.exists() && !prev.exists()
  isUpdateObject(): next.exists() && prev.exists()

rules:
  users:
    $user_id:
      .write: isNewObject() && (isAuthed() || isUpdateObject()) && isUser($user_id)
```

I get the following output:

``` json
{
  "rules": {
    "users": {
      "$user_id": {
        ".write": "newData.exists() && !data.exists() && (auth !== null || newData.exists() && data.exists()) && auth.uid === $user_id"
      }
    }
  }
}
```

In this example parenthesis are needed, and as a result are preserved.
